# Generated by Django 3.1.1 on 2020-11-01 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('excavation', 'excavation'), ('foundation', 'foundation'), ('finished', 'finished')], default='excavation', max_length=20)),
                ('excavation_img', models.ImageField(default='default.png', upload_to='construction')),
                ('foundation_img', models.ImageField(default='default.png', upload_to='construction')),
                ('finished_img', models.ImageField(default='default.png', upload_to='construction')),
                ('estimated_cost', models.IntegerField(default=2000000)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('material_type', models.CharField(choices=[('Cement', 'Cement'), ('Steel', 'Steel'), ('Sanitary_ware', 'Sanitary_ware'), ('Sand', 'Sand'), ('Aggregate', 'Aggregate'), ('Tiles', 'Tiles'), ('CP_Fitting', 'CP_Fitting'), ('Paints', 'Paints'), ('Other', 'Other')], default='Other', max_length=20)),
                ('cost', models.IntegerField()),
                ('material_img', models.ImageField(default='default.png', upload_to='material')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wage', models.FloatField(blank=True, default=0, null=True)),
                ('prev_record', models.IntegerField()),
                ('work_done', models.CharField(choices=[('Electrician', 'Electrician'), ('Carpenter', 'Carpenter'), ('Plumber', 'Plumber'), ('Painter', 'Painter'), ('Cons_worker', 'Cons_worker'), ('None', 'None')], default='None', max_length=100)),
                ('construction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.construction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('wall_thickness', models.IntegerField()),
                ('floors', models.IntegerField()),
                ('parking', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('modification', 'Ask For Modification'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('drawing_plan', models.ImageField(blank=True, default='default.png', upload_to='drawing')),
                ('sectional_plan', models.ImageField(blank=True, default='default.png', upload_to='sectional')),
                ('floor_plan', models.ImageField(blank=True, default='default.png', upload_to='floor')),
                ('elevated_plan', models.ImageField(blank=True, default='default.png', upload_to='elevated')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
            ],
        ),
        migrations.AddField(
            model_name='construction',
            name='materials',
            field=models.ManyToManyField(blank=True, to='accounts.Material'),
        ),
        migrations.AddField(
            model_name='construction',
            name='plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.plan'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
