# Generated by Django 3.1.2 on 2020-10-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='drawing_plan',
            field=models.ImageField(blank=True, default='default.png', upload_to='drawing'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='elevated_plan',
            field=models.ImageField(blank=True, default='default.png', upload_to='elevated'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='floor_plan',
            field=models.ImageField(blank=True, default='default.png', upload_to='floor'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='sectional_plan',
            field=models.ImageField(blank=True, default='default.png', upload_to='sectional'),
        ),
    ]
