# Generated by Django 3.1.1 on 2020-10-28 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_admin_client_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('wall_thickness', models.IntegerField()),
                ('floors', models.IntegerField()),
                ('parking', models.BooleanField(default=True)),
                ('drawing_plan', models.ImageField(blank=True, upload_to='./Drawing')),
                ('sectional_plan', models.ImageField(blank=True, upload_to='./Sectional')),
                ('floor_plan', models.ImageField(blank=True, upload_to='./Floor')),
                ('elevated_plan', models.ImageField(blank=True, upload_to='./Elevated')),
            ],
        ),
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.plan')),
                ('workers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.worker')),
            ],
        ),
    ]
