# Generated by Django 3.1.1 on 2020-10-31 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201031_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='wage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
