# Generated by Django 3.1.1 on 2020-10-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201031_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('material_type', models.CharField(choices=[('Cement', 'Cement'), ('Steel', 'Steel'), ('Sanitary_ware', 'Sanitary_ware'), ('Sand', 'Sand'), ('Aggregate', 'Aggregate'), ('Tiles', 'Tiles'), ('CP_Fitting', 'CP_Fitting'), ('Paints', 'Paints'), ('Other', 'Other')], default='Other', max_length=20)),
                ('cost', models.IntegerField()),
                ('material_img', models.ImageField(blank=True, upload_to='material')),
            ],
        ),
        migrations.AddField(
            model_name='construction',
            name='excavation_img',
            field=models.ImageField(blank=True, null=True, upload_to='construction'),
        ),
        migrations.AddField(
            model_name='construction',
            name='finished_img',
            field=models.ImageField(blank=True, null=True, upload_to='construction'),
        ),
        migrations.AddField(
            model_name='construction',
            name='foundation_img',
            field=models.ImageField(blank=True, null=True, upload_to='construction'),
        ),
        migrations.AddField(
            model_name='construction',
            name='materials',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Material'),
        ),
    ]
