# Generated by Django 3.1.1 on 2020-10-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201031_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='worker',
            name='work_done',
            field=models.CharField(choices=[('Electrician', 'Electrician'), ('Carpenter', 'Carpenter'), ('Plumber', 'Plumber'), ('Painter', 'Painter'), ('Cons_worker', 'Cons_worker'), ('None', 'None')], default='None', max_length=100),
        ),
    ]
