# Generated by Django 3.1.1 on 2020-10-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201031_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='excavation_img',
            field=models.ImageField(default='default.png', upload_to='construction'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='finished_img',
            field=models.ImageField(default='default.png', upload_to='construction'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='foundation_img',
            field=models.ImageField(default='default.png', upload_to='construction'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_img',
            field=models.ImageField(default='default.png', upload_to='material'),
        ),
    ]
