# Generated by Django 3.1.1 on 2020-10-31 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201031_0957'),
        ('accounts', '0007_auto_20201031_1219'),
    ]

    operations = [
    ]
